### Load the dataset

In [2]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../data/processed/dataset_final_entropy.csv")

# Display the first 5 rows
df.head()

,place_id,latitude,longitude,search_area,Demand,Accessibility,Competition,Population,label,Demand_contribution,Accessibility_contribution,Competition_contribution,Population_contribution,feasibility_score,cluster,feasibility_label
0,ChIJsZ5mY70Z6zkRRBczgL9a8ms,27.699546,85.337687,Baneshwor,0.2995,0.4165,0.4850,0.4712,1,0.189981,0.048357,0.055860,0.157250,45.144791,1,High
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,27.692262,85.336472,Baneshwor,0.4008,0.4903,0.4213,0.4351,1,0.254239,0.056925,0.042963,0.145203,49.932931,1,High
2,ChIJTdMmLgAZ6zkR84zXOWwdgPE,27.689064,85.334295,Baneshwor,0.4458,0.5682,0.4101,0.4219,1,0.282783,0.065969,0.040695,0.140798,53.024568,1,High
3,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,27.681549,85.341340,Baneshwor,0.2319,0.5350,0.4891,0.5552,1,0.147101,0.062115,0.056690,0.185283,45.118830,1,High
4,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27.688812,85.334080,Baneshwor,0.4351,0.5848,0.4088,0.4260,1,0.275996,0.067896,0.040432,0.142166,52.649073,1,High

In [3]:
df.describe()

,latitude,longitude,Demand,Accessibility,Competition,Population,label,Demand_contribution,Accessibility_contribution,Competition_contribution,Population_contribution,feasibility_score,cluster
count,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000
mean,27.691487,85.337263,0.236463,0.396715,0.482614,0.364638,0.352828,0.149995,0.046059,0.055377,0.121688,37.311962,0.858581
std,0.019222,0.040978,0.143550,0.113498,0.108753,0.200844,0.477907,0.091058,0.013177,0.022019,0.067026,14.283425,0.806138
min,27.612834,85.253978,0.000000,0.000000,0.209100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.102881,0.000000
25%,27.675552,85.311755,0.126075,0.333725,0.426575,0.242200,0.000000,0.079973,0.038746,0.044031,0.080828,27.123042,0.000000
50%,27.687821,85.328256,0.226150,0.395950,0.491600,0.352000,0.000000,0.143453,0.045971,0.057196,0.117471,36.724943,1.000000
75%,27.707763,85.355805,0.329325,0.469125,0.525300,0.475650,1.000000,0.208900,0.054466,0.064019,0.158736,47.718838,2.000000
max,27.748779,85.458855,0.659300,0.757400,1.000000,1.000000,1.000000,0.418212,0.087936,0.160128,0.333723,81.596636,2.000000

## Check dataset info

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4172 entries, 0 to 4171
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   place_id                    4172 non-null   object
 1   latitude                    4172 non-null   float64
 2   longitude                   4172 non-null   float64
 3   search_area                 4172 non-null   object
 4   Demand                      4172 non-null   float64
 5   Accessibility               4172 non-null   float64
 6   Competition                 4172 non-null   float64
 7   Population                  4172 non-null   float64
 8   label                       4172 non-null   int64
 9   Demand_contribution         4172 non-null   float64
 10  Accessibility_contribution  4172 non-null   float64
 11  Competition_contribution    4172 non-null   float64
 12  Population_contribution     4172 non-null   float64
 13  feasibility_score           4172 non-null   float64
 14  cluster                     4172 non-null   int64
 15  feasibility_label           4172 non-null   object
dtypes: float64(11), int64(2), object(3)
memory usage: 521.6+ KB

In [5]:
df.columns

Index(['place_id', 'latitude', 'longitude', 'search_area', 'Demand',
       'Accessibility', 'Competition', 'Population', 'label',
       'Demand_contribution', 'Accessibility_contribution',
       'Competition_contribution', 'Population_contribution',
       'feasibility_score', 'cluster', 'feasibility_label'],
      dtype='object')

### Check for missing values

In [6]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

Series([], dtype: int64)

### all the unique  primary type

In [7]:
# Show all unique primary types
print(df["primary_type"].dropna().unique())

KeyError: 'primary_type'

### Check missing target Values

In [ ]:
print(df["feasibility_label"].isnull().sum())

0

### Validate the target labels

In [ ]:
print(df["feasibility_label"].unique())

<StringArray>
['Moderate', 'High', 'Low']
Length: 3, dtype: str

### Check for Duplicate Rows

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

#### Check Data Types

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4172 entries, 0 to 4171
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   place_id                                 4172 non-null   str
 1   latitude                                 4172 non-null   float64
 2   longitude                                4172 non-null   float64
 3   search_area                              4172 non-null   str
 4   primary_type                             1466 non-null   str
 5   searched_as                              1472 non-null   str
 6   label                                    4172 non-null   int64
 7   feasibility_score                        4172 non-null   float64
 8   feasibility_label                        4172 non-null   str
 9   cluster                                  4172 non-null   int64
 10  bank_count_500m                          4172 non-null   int64
 11  bank_count_500m_normalized               4172 non-null   float64
 12  bank_count_500m_contribution             4172 non-null   float64
 13  bus_stop_count_500m                      4172 non-null   int64
 14  bus_stop_count_500m_normalized           4172 non-null   float64
 15  bus_stop_count_500m_contribution         4172 non-null   float64
 16  cinema_count_500m                        4172 non-null   int64
 17  cinema_count_500m_normalized             4172 non-null   float64
 18  cinema_count_500m_contribution           4172 non-null   float64
 19  clinic_count_500m                        4172 non-null   int64
 20  clinic_count_500m_normalized             4172 non-null   float64
 21  clinic_count_500m_contribution           4172 non-null   float64
 22  college_count_500m                       4172 non-null   int64
 23  college_count_500m_normalized            4172 non-null   float64
 24  college_count_500m_contribution          4172 non-null   float64
 25  hospital_count_500m                      4172 non-null   int64
 26  hospital_count_500m_normalized           4172 non-null   float64
 27  hospital_count_500m_contribution         4172 non-null   float64
 28  museum_count_500m                        4172 non-null   int64
 29  museum_count_500m_normalized             4172 non-null   float64
 30  museum_count_500m_contribution           4172 non-null   float64
 31  office_count_500m                        4172 non-null   int64
 32  office_count_500m_normalized             4172 non-null   float64
 33  office_count_500m_contribution           4172 non-null   float64
 34  parking_space_count_500m                 4172 non-null   int64
 35  parking_space_count_500m_normalized      4172 non-null   float64
 36  parking_space_count_500m_contribution    4172 non-null   float64
 37  recreation_count_500m                    4172 non-null   int64
 38  recreation_count_500m_normalized         4172 non-null   float64
 39  recreation_count_500m_contribution       4172 non-null   float64
 40  retail_count_500m                        4172 non-null   int64
 41  retail_count_500m_normalized             4172 non-null   float64
 42  retail_count_500m_contribution           4172 non-null   float64
 43  school_count_500m                        4172 non-null   int64
 44  school_count_500m_normalized             4172 non-null   float64
 45  school_count_500m_contribution           4172 non-null   float64
 46  temple_count_500m                        4172 non-null   int64
 47  temple_count_500m_normalized             4172 non-null   float64
 48  temple_count_500m_contribution           4172 non-null   float64
 49  nearest_restaurant_m                     4172 non-null   float64
 50  nearest_restaurant_m_normalized          4172 non-null   float64
 51  nearest_restaurant_m_contribution        4172 non-null   float64
 52  competitor_count_500m                    4172 non-null   int64
 53  competitor_count_500m_normalized         4172 non-null   float64
 54  competitor_count_500m_contribution       4172 non-null   float64
 55  avg_restaurant_rating_500m               4172 non-null   float64
 56  avg_restaurant_rating_500m_normalized    4172 non-null   float64
 57  avg_restaurant_rating_500m_contribution  4172 non-null   float64
 58  avg_review_ratings_500m                  4172 non-null   float64
 59  avg_review_ratings_500m_normalized       4172 non-null   float64
 60  avg_review_ratings_500m_contribution     4172 non-null   float64
dtypes: float64(40), int64(16), str(5)
memory usage: 1.9 MB

### Check impossible negative values

In [ ]:
feature_cols = [
    "bank_count_500m",
    "bus_stop_count_500m",
    "cinema_count_500m",
    "clinic_count_500m",
    "college_count_500m",
    "hospital_count_500m",
    "museum_count_500m",
    "office_count_500m",
    "parking_space_count_500m",
    "recreation_count_500m",
    "retail_count_500m",
    "school_count_500m",
    "temple_count_500m",
    "nearest_restaurant_m",
    "competitor_count_500m",
    "avg_restaurant_rating_500m",
    "avg_review_ratings_500m"
]
for col in feature_cols:
    negative_count = (df[col] < 0).sum()

    if negative_count > 0:
        print(col, negative_count)

### Data Validation

In [ ]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

latitude: Min = 27.6128344, Max = 27.7487787
longitude: Min = 85.2539784, Max = 85.4588553
label: Min = 0, Max = 1
feasibility_score: Min = 0.8835409719648165, Max = 47.39983349540176
cluster: Min = 0, Max = 2
bank_count_500m: Min = 0, Max = 95
bank_count_500m_normalized: Min = 0.0, Max = 1.0
bank_count_500m_contribution: Min = 0.0, Max = 0.0689651005089675
bus_stop_count_500m: Min = 0, Max = 11
bus_stop_count_500m_normalized: Min = 0.0, Max = 1.0
bus_stop_count_500m_contribution: Min = 0.0, Max = 0.0867300556767059
cinema_count_500m: Min = 0, Max = 7
cinema_count_500m_normalized: Min = 0.0, Max = 1.0
cinema_count_500m_contribution: Min = 0.0, Max = 0.1769182086652755
clinic_count_500m: Min = 0, Max = 76
clinic_count_500m_normalized: Min = 0.0, Max = 1.0
clinic_count_500m_contribution: Min = 0.0, Max = 0.0459934211505632
college_count_500m: Min = 0, Max = 64
college_count_500m_normalized: Min = 0.0, Max = 1.0
college_count_500m_contribution: Min = 0.0, Max = 0.0692606268816134
hospital_count_500m: Min = 0, Max = 31
hospital_count_500m_normalized: Min = 0.0, Max = 1.0
hospital_count_500m_contribution: Min = 0.0, Max = 0.0415505064564536
museum_count_500m: Min = 0, Max = 36
museum_count_500m_normalized: Min = 0.0, Max = 1.0
museum_count_500m_contribution: Min = 0.0, Max = 0.1605770777299426
office_count_500m: Min = 0, Max = 103
office_count_500m_normalized: Min = 0.0, Max = 1.0
office_count_500m_contribution: Min = 0.0, Max = 0.0420631967502487
parking_space_count_500m: Min = 0, Max = 23
parking_space_count_500m_normalized: Min = 0.0, Max = 1.0
parking_space_count_500m_contribution: Min = 0.0, Max = 0.0741060804999461
recreation_count_500m: Min = 0, Max = 77
recreation_count_500m_normalized: Min = 0.0, Max = 1.0
recreation_count_500m_contribution: Min = 0.0, Max = 0.0354047387306011
retail_count_500m: Min = 0, Max = 158
retail_count_500m_normalized: Min = 0.0, Max = 1.0
retail_count_500m_contribution: Min = 0.0, Max = 0.024260048758469
school_count_500m: Min = 0, Max = 60
school_count_500m_normalized: Min = 0.0, Max = 1.0
school_count_500m_contribution: Min = 0.0, Max = 0.0293169242312025
temple_count_500m: Min = 0, Max = 104
temple_count_500m_normalized: Min = 0.0, Max = 1.0
temple_count_500m_contribution: Min = 0.0, Max = 0.0698295813006479
nearest_restaurant_m: Min = 0.0, Max = 4315.280344854998
nearest_restaurant_m_normalized: Min = 0.0, Max = 1.0
nearest_restaurant_m_contribution: Min = 0.0, Max = 0.055327435619664
competitor_count_500m: Min = 0, Max = 123
competitor_count_500m_normalized: Min = 0.0, Max = 1.0
competitor_count_500m_contribution: Min = 0.0, Max = 0.0077339944723202
avg_restaurant_rating_500m: Min = 1.0, Max = 5.0
avg_restaurant_rating_500m_normalized: Min = 0.0, Max = 1.0
avg_restaurant_rating_500m_contribution: Min = 0.0, Max = 0.0115625923433875
avg_review_ratings_500m: Min = 1.0, Max = 1471.0
avg_review_ratings_500m_normalized: Min = 0.0, Max = 1.0
avg_review_ratings_500m_contribution: Min = 0.0, Max = 0.0004004102239906