### Load the dataset

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../data/processed/dataset_labelled_with_score.csv")

# Display the first 5 rows
df.head()

,place_id,latitude,longitude,search_area,primary_type,searched_as,label,feasibility_score,feasibility_label,cluster,...,nearest_restaurant_m_contribution,competitor_count_500m,competitor_count_500m_normalized,competitor_count_500m_contribution,avg_restaurant_rating_500m,avg_restaurant_rating_500m_normalized,avg_restaurant_rating_500m_contribution,avg_review_ratings_500m,avg_review_ratings_500m_normalized,avg_review_ratings_500m_contribution
0,ChIJsZ5mY70Z6zkRRBczgL9a8ms,27.699546,85.337687,Baneshwor,restaurant,restaurant,1,18.652333,Moderate,0,...,0.000851,20,0.837398,0.006476,4.265000,0.183750,0.002125,87.700000,0.941020,0.000377
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,27.692262,85.336472,Baneshwor,restaurant,restaurant,1,27.954012,High,2,...,0.000050,44,0.642276,0.004967,4.247727,0.188068,0.002175,159.477273,0.892192,0.000357
2,ChIJTdMmLgAZ6zkR84zXOWwdgPE,27.689064,85.334295,Baneshwor,restaurant,restaurant,1,37.665885,High,2,...,0.000449,48,0.609756,0.004716,4.231250,0.192187,0.002222,201.104167,0.863875,0.000346
3,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,27.681549,85.341340,Baneshwor,restaurant,restaurant,1,12.152369,Low,1,...,0.000067,14,0.886179,0.006854,4.371429,0.157143,0.001817,83.214286,0.944072,0.000378
4,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27.688812,85.334080,Baneshwor,restaurant,restaurant,1,37.304810,High,2,...,0.000449,47,0.617886,0.004779,4.270213,0.182447,0.002110,200.893617,0.864018,0.000346

In [2]:
df.describe()

,latitude,longitude,label,feasibility_score,cluster,bank_count_500m,bank_count_500m_normalized,bank_count_500m_contribution,bus_stop_count_500m,bus_stop_count_500m_normalized,...,nearest_restaurant_m_contribution,competitor_count_500m,competitor_count_500m_normalized,competitor_count_500m_contribution,avg_restaurant_rating_500m,avg_restaurant_rating_500m_normalized,avg_restaurant_rating_500m_contribution,avg_review_ratings_500m,avg_review_ratings_500m_normalized,avg_review_ratings_500m_contribution
count,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,...,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000,4172.000000
mean,27.691487,85.337263,0.352828,17.381667,0.811361,18.588686,0.195670,0.013494,2.081975,0.189270,...,0.002046,26.002397,0.788598,0.006099,4.418600,0.145350,0.001681,121.139196,0.918273,0.000368
std,0.019222,0.040978,0.477907,11.319171,0.751015,18.570930,0.195483,0.013482,2.220843,0.201895,...,0.002221,27.755422,0.225654,0.001745,0.223350,0.055838,0.000646,95.916450,0.065249,0.000026
min,27.612834,85.253978,0.000000,0.883541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,27.675552,85.311755,0.000000,8.377579,0.000000,4.000000,0.042105,0.002904,0.000000,0.000000,...,0.000807,7.000000,0.707317,0.005470,4.294737,0.115385,0.001334,50.621032,0.878424,0.000352
50%,27.687821,85.328256,0.000000,15.508111,1.000000,14.000000,0.147368,0.010163,1.000000,0.090909,...,0.001535,15.000000,0.878049,0.006791,4.410000,0.147500,0.001705,97.071429,0.934645,0.000374
75%,27.707763,85.355805,1.000000,24.359674,1.000000,26.000000,0.273684,0.018875,3.000000,0.272727,...,0.002646,36.000000,0.943089,0.007294,4.538462,0.176316,0.002039,179.716912,0.966244,0.000387
max,27.748779,85.458855,1.000000,47.399833,2.000000,95.000000,1.000000,0.068965,11.000000,1.000000,...,0.055327,123.000000,1.000000,0.007734,5.000000,1.000000,0.011563,1471.000000,1.000000,0.000400

## Check dataset info

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4172 entries, 0 to 4171
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   place_id                                 4172 non-null   str
 1   latitude                                 4172 non-null   float64
 2   longitude                                4172 non-null   float64
 3   search_area                              4172 non-null   str
 4   primary_type                             1466 non-null   str
 5   searched_as                              1472 non-null   str
 6   label                                    4172 non-null   int64
 7   feasibility_score                        4172 non-null   float64
 8   feasibility_label                        4172 non-null   str
 9   cluster                                  4172 non-null   int64
 10  bank_count_500m                          4172 non-null   int64
 11  bank_count_500m_normalized               4172 non-null   float64
 12  bank_count_500m_contribution             4172 non-null   float64
 13  bus_stop_count_500m                      4172 non-null   int64
 14  bus_stop_count_500m_normalized           4172 non-null   float64
 15  bus_stop_count_500m_contribution         4172 non-null   float64
 16  cinema_count_500m                        4172 non-null   int64
 17  cinema_count_500m_normalized             4172 non-null   float64
 18  cinema_count_500m_contribution           4172 non-null   float64
 19  clinic_count_500m                        4172 non-null   int64
 20  clinic_count_500m_normalized             4172 non-null   float64
 21  clinic_count_500m_contribution           4172 non-null   float64
 22  college_count_500m                       4172 non-null   int64
 23  college_count_500m_normalized            4172 non-null   float64
 24  college_count_500m_contribution          4172 non-null   float64
 25  hospital_count_500m                      4172 non-null   int64
 26  hospital_count_500m_normalized           4172 non-null   float64
 27  hospital_count_500m_contribution         4172 non-null   float64
 28  museum_count_500m                        4172 non-null   int64
 29  museum_count_500m_normalized             4172 non-null   float64
 30  museum_count_500m_contribution           4172 non-null   float64
 31  office_count_500m                        4172 non-null   int64
 32  office_count_500m_normalized             4172 non-null   float64
 33  office_count_500m_contribution           4172 non-null   float64
 34  parking_space_count_500m                 4172 non-null   int64
 35  parking_space_count_500m_normalized      4172 non-null   float64
 36  parking_space_count_500m_contribution    4172 non-null   float64
 37  recreation_count_500m                    4172 non-null   int64
 38  recreation_count_500m_normalized         4172 non-null   float64
 39  recreation_count_500m_contribution       4172 non-null   float64
 40  retail_count_500m                        4172 non-null   int64
 41  retail_count_500m_normalized             4172 non-null   float64
 42  retail_count_500m_contribution           4172 non-null   float64
 43  school_count_500m                        4172 non-null   int64
 44  school_count_500m_normalized             4172 non-null   float64
 45  school_count_500m_contribution           4172 non-null   float64
 46  temple_count_500m                        4172 non-null   int64
 47  temple_count_500m_normalized             4172 non-null   float64
 48  temple_count_500m_contribution           4172 non-null   float64
 49  nearest_restaurant_m                     4172 non-null   float64
 50  nearest_restaurant_m_normalized          4172 non-null   float64
 51  nearest_restaurant_m_contribution        4172 non-null   float64
 52  competitor_count_500m                    4172 non-null   int64
 53  competitor_count_500m_normalized         4172 non-null   float64
 54  competitor_count_500m_contribution       4172 non-null   float64
 55  avg_restaurant_rating_500m               4172 non-null   float64
 56  avg_restaurant_rating_500m_normalized    4172 non-null   float64
 57  avg_restaurant_rating_500m_contribution  4172 non-null   float64
 58  avg_review_ratings_500m                  4172 non-null   float64
 59  avg_review_ratings_500m_normalized       4172 non-null   float64
 60  avg_review_ratings_500m_contribution     4172 non-null   float64
dtypes: float64(40), int64(16), str(5)
memory usage: 1.9 MB

In [4]:
df.columns

Index(['place_id', 'latitude', 'longitude', 'search_area', 'primary_type',
       'searched_as', 'label', 'feasibility_score', 'feasibility_label',
       'cluster', 'bank_count_500m', 'bank_count_500m_normalized',
       'bank_count_500m_contribution', 'bus_stop_count_500m',
       'bus_stop_count_500m_normalized', 'bus_stop_count_500m_contribution',
       'cinema_count_500m', 'cinema_count_500m_normalized',
       'cinema_count_500m_contribution', 'clinic_count_500m',
       'clinic_count_500m_normalized', 'clinic_count_500m_contribution',
       'college_count_500m', 'college_count_500m_normalized',
       'college_count_500m_contribution', 'hospital_count_500m',
       'hospital_count_500m_normalized', 'hospital_count_500m_contribution',
       'museum_count_500m', 'museum_count_500m_normalized',
       'museum_count_500m_contribution', 'office_count_500m',
       'office_count_500m_normalized', 'office_count_500m_contribution',
       'parking_space_count_500m', 'parking_space_count_500m_normalized',
       'parking_space_count_500m_contribution', 'recreation_count_500m',
       'recreation_count_500m_normalized',
       'recreation_count_500m_contribution', 'retail_count_500m',
       'retail_count_500m_normalized', 'retail_count_500m_contribution',
       'school_count_500m', 'school_count_500m_normalized',
       'school_count_500m_contribution', 'temple_count_500m',
       'temple_count_500m_normalized', 'temple_count_500m_contribution',
       'nearest_restaurant_m', 'nearest_restaurant_m_normalized',
       'nearest_restaurant_m_contribution', 'competitor_count_500m',
       'competitor_count_500m_normalized',
       'competitor_count_500m_contribution', 'avg_restaurant_rating_500m',
       'avg_restaurant_rating_500m_normalized',
       'avg_restaurant_rating_500m_contribution', 'avg_review_ratings_500m',
       'avg_review_ratings_500m_normalized',
       'avg_review_ratings_500m_contribution'],
      dtype='str')

### Check for missing values

In [5]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

primary_type    2706
searched_as     2700
dtype: int64

### all the unique  primary type

In [6]:
# Show all unique primary types
print(df["primary_type"].dropna().unique())

<StringArray>
[                'restaurant',        'barbecue_restaurant',
          'family_restaurant',       'fast_food_restaurant',
         'tibetan_restaurant',       'hamburger_restaurant',
          'korean_restaurant',           'asian_restaurant',
                       'cafe',                'coffee_shop',
                  'cafeteria', 'korean_barbecue_restaurant',
                 'sports_bar',                        'bar',
                 'lounge_bar',              'bar_and_grill',
                  'cake_shop',                     'bakery',
    'educational_institution',           'ramen_restaurant',
          'indian_restaurant',                'steak_house',
            'thai_restaurant',           'pizza_restaurant',
        'japanese_restaurant',        'shawarma_restaurant',
         'western_restaurant',           'halal_restaurant',
                 'food_store',                        'pub',
               'dessert_shop',                      'store',
                      'hotel',      'vegetarian_restaurant',
                'guest_house',         'chinese_restaurant',
                  'tea_house',               'manufacturer',
         'italian_restaurant',                 'food_court',
    'north_indian_restaurant',         'indoor_golf_course',
               'cocktail_bar',          'brunch_restaurant',
    'asian_fusion_restaurant',         'spanish_restaurant',
           'vegan_restaurant',              'meal_takeaway',
    'south_indian_restaurant',                'noodle_shop',
     'fine_dining_restaurant',  'latin_american_restaurant',
        'american_restaurant',                  'irish_pub',
            'coffee_roastery']
Length: 55, dtype: str

### Check missing target Values

In [11]:
print(df["feasibility_label"].isnull().sum())

0

### Validate the target labels

In [12]:
print(df["feasibility_label"].unique())

<StringArray>
['Moderate', 'High', 'Low']
Length: 3, dtype: str

### Check for Duplicate Rows

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

#### Check Data Types

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4172 entries, 0 to 4171
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   place_id                                 4172 non-null   str
 1   latitude                                 4172 non-null   float64
 2   longitude                                4172 non-null   float64
 3   search_area                              4172 non-null   str
 4   primary_type                             1466 non-null   str
 5   searched_as                              1472 non-null   str
 6   label                                    4172 non-null   int64
 7   feasibility_score                        4172 non-null   float64
 8   feasibility_label                        4172 non-null   str
 9   cluster                                  4172 non-null   int64
 10  bank_count_500m                          4172 non-null   int64
 11  bank_count_500m_normalized               4172 non-null   float64
 12  bank_count_500m_contribution             4172 non-null   float64
 13  bus_stop_count_500m                      4172 non-null   int64
 14  bus_stop_count_500m_normalized           4172 non-null   float64
 15  bus_stop_count_500m_contribution         4172 non-null   float64
 16  cinema_count_500m                        4172 non-null   int64
 17  cinema_count_500m_normalized             4172 non-null   float64
 18  cinema_count_500m_contribution           4172 non-null   float64
 19  clinic_count_500m                        4172 non-null   int64
 20  clinic_count_500m_normalized             4172 non-null   float64
 21  clinic_count_500m_contribution           4172 non-null   float64
 22  college_count_500m                       4172 non-null   int64
 23  college_count_500m_normalized            4172 non-null   float64
 24  college_count_500m_contribution          4172 non-null   float64
 25  hospital_count_500m                      4172 non-null   int64
 26  hospital_count_500m_normalized           4172 non-null   float64
 27  hospital_count_500m_contribution         4172 non-null   float64
 28  museum_count_500m                        4172 non-null   int64
 29  museum_count_500m_normalized             4172 non-null   float64
 30  museum_count_500m_contribution           4172 non-null   float64
 31  office_count_500m                        4172 non-null   int64
 32  office_count_500m_normalized             4172 non-null   float64
 33  office_count_500m_contribution           4172 non-null   float64
 34  parking_space_count_500m                 4172 non-null   int64
 35  parking_space_count_500m_normalized      4172 non-null   float64
 36  parking_space_count_500m_contribution    4172 non-null   float64
 37  recreation_count_500m                    4172 non-null   int64
 38  recreation_count_500m_normalized         4172 non-null   float64
 39  recreation_count_500m_contribution       4172 non-null   float64
 40  retail_count_500m                        4172 non-null   int64
 41  retail_count_500m_normalized             4172 non-null   float64
 42  retail_count_500m_contribution           4172 non-null   float64
 43  school_count_500m                        4172 non-null   int64
 44  school_count_500m_normalized             4172 non-null   float64
 45  school_count_500m_contribution           4172 non-null   float64
 46  temple_count_500m                        4172 non-null   int64
 47  temple_count_500m_normalized             4172 non-null   float64
 48  temple_count_500m_contribution           4172 non-null   float64
 49  nearest_restaurant_m                     4172 non-null   float64
 50  nearest_restaurant_m_normalized          4172 non-null   float64
 51  nearest_restaurant_m_contribution        4172 non-null   float64
 52  competitor_count_500m                    4172 non-null   int64
 53  competitor_count_500m_normalized         4172 non-null   float64
 54  competitor_count_500m_contribution       4172 non-null   float64
 55  avg_restaurant_rating_500m               4172 non-null   float64
 56  avg_restaurant_rating_500m_normalized    4172 non-null   float64
 57  avg_restaurant_rating_500m_contribution  4172 non-null   float64
 58  avg_review_ratings_500m                  4172 non-null   float64
 59  avg_review_ratings_500m_normalized       4172 non-null   float64
 60  avg_review_ratings_500m_contribution     4172 non-null   float64
dtypes: float64(40), int64(16), str(5)
memory usage: 1.9 MB

### Check impossible negative values

In [13]:
feature_cols = [
    "bank_count_500m",
    "bus_stop_count_500m",
    "cinema_count_500m",
    "clinic_count_500m",
    "college_count_500m",
    "hospital_count_500m",
    "museum_count_500m",
    "office_count_500m",
    "parking_space_count_500m",
    "recreation_count_500m",
    "retail_count_500m",
    "school_count_500m",
    "temple_count_500m",
    "nearest_restaurant_m",
    "competitor_count_500m",
    "avg_restaurant_rating_500m",
    "avg_review_ratings_500m"
]
for col in feature_cols:
    negative_count = (df[col] < 0).sum()

    if negative_count > 0:
        print(col, negative_count)

### Data Validation

In [14]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

latitude: Min = 27.6128344, Max = 27.7487787
longitude: Min = 85.2539784, Max = 85.4588553
label: Min = 0, Max = 1
feasibility_score: Min = 0.8835409719648165, Max = 47.39983349540176
cluster: Min = 0, Max = 2
bank_count_500m: Min = 0, Max = 95
bank_count_500m_normalized: Min = 0.0, Max = 1.0
bank_count_500m_contribution: Min = 0.0, Max = 0.0689651005089675
bus_stop_count_500m: Min = 0, Max = 11
bus_stop_count_500m_normalized: Min = 0.0, Max = 1.0
bus_stop_count_500m_contribution: Min = 0.0, Max = 0.0867300556767059
cinema_count_500m: Min = 0, Max = 7
cinema_count_500m_normalized: Min = 0.0, Max = 1.0
cinema_count_500m_contribution: Min = 0.0, Max = 0.1769182086652755
clinic_count_500m: Min = 0, Max = 76
clinic_count_500m_normalized: Min = 0.0, Max = 1.0
clinic_count_500m_contribution: Min = 0.0, Max = 0.0459934211505632
college_count_500m: Min = 0, Max = 64
college_count_500m_normalized: Min = 0.0, Max = 1.0
college_count_500m_contribution: Min = 0.0, Max = 0.0692606268816134
hospital_count_500m: Min = 0, Max = 31
hospital_count_500m_normalized: Min = 0.0, Max = 1.0
hospital_count_500m_contribution: Min = 0.0, Max = 0.0415505064564536
museum_count_500m: Min = 0, Max = 36
museum_count_500m_normalized: Min = 0.0, Max = 1.0
museum_count_500m_contribution: Min = 0.0, Max = 0.1605770777299426
office_count_500m: Min = 0, Max = 103
office_count_500m_normalized: Min = 0.0, Max = 1.0
office_count_500m_contribution: Min = 0.0, Max = 0.0420631967502487
parking_space_count_500m: Min = 0, Max = 23
parking_space_count_500m_normalized: Min = 0.0, Max = 1.0
parking_space_count_500m_contribution: Min = 0.0, Max = 0.0741060804999461
recreation_count_500m: Min = 0, Max = 77
recreation_count_500m_normalized: Min = 0.0, Max = 1.0
recreation_count_500m_contribution: Min = 0.0, Max = 0.0354047387306011
retail_count_500m: Min = 0, Max = 158
retail_count_500m_normalized: Min = 0.0, Max = 1.0
retail_count_500m_contribution: Min = 0.0, Max = 0.024260048758469
school_count_500m: Min = 0, Max = 60
school_count_500m_normalized: Min = 0.0, Max = 1.0
school_count_500m_contribution: Min = 0.0, Max = 0.0293169242312025
temple_count_500m: Min = 0, Max = 104
temple_count_500m_normalized: Min = 0.0, Max = 1.0
temple_count_500m_contribution: Min = 0.0, Max = 0.0698295813006479
nearest_restaurant_m: Min = 0.0, Max = 4315.280344854998
nearest_restaurant_m_normalized: Min = 0.0, Max = 1.0
nearest_restaurant_m_contribution: Min = 0.0, Max = 0.055327435619664
competitor_count_500m: Min = 0, Max = 123
competitor_count_500m_normalized: Min = 0.0, Max = 1.0
competitor_count_500m_contribution: Min = 0.0, Max = 0.0077339944723202
avg_restaurant_rating_500m: Min = 1.0, Max = 5.0
avg_restaurant_rating_500m_normalized: Min = 0.0, Max = 1.0
avg_restaurant_rating_500m_contribution: Min = 0.0, Max = 0.0115625923433875
avg_review_ratings_500m: Min = 1.0, Max = 1471.0
avg_review_ratings_500m_normalized: Min = 0.0, Max = 1.0
avg_review_ratings_500m_contribution: Min = 0.0, Max = 0.0004004102239906