In [19]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../data/processed/final_dataset.csv")

# Display the first 5 rows
df.head()

,place_id,restaurant_name,address,latitude,longitude,restaurant_rating,user_rating_count,price_level,primary_type,all_types,...,office_count_500m,parking_space_count_500m,recreation_count_500m,retail_count_500m,school_count_500m,temple_count_500m,competitor_count_500m,avg_restaurant_rating_500m,avg_review_ratings_500m,nearest_restaurant_m
0,ChIJsZ5mY70Z6zkRRBczgL9a8ms,JAR - Just Another Restaurant,"Pipal Bot Marg, Kathmandu 56900, Nepal",27.699546,85.337687,4.3,443.0,PRICE_LEVEL_MODERATE,restaurant,restaurant|food|point_of_interest|establishment,...,53,5,21,52,35,15,20,4.265000,87.700000,66.240461
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.4,1180.0,PRICE_LEVEL_EXPENSIVE,restaurant,restaurant|food|point_of_interest|establishment,...,66,6,19,83,48,17,44,4.247727,159.477273,3.882433
2,ChIJTdMmLgAZ6zkR84zXOWwdgPE,Pink Putali Restaurant & Bar,"4 Chhakku Bakku Marg, Kathmandu 44600, Nepal",27.689064,85.334295,4.8,90.0,NaN,restaurant,restaurant|food|point_of_interest|establishment,...,67,11,18,67,30,6,47,4.234043,204.255319,35.077195
3,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,Munch N More Restaurant and Bar,"Janata Sadak, Kathmandu 44600, Nepal",27.681549,85.341340,4.9,60.0,NaN,restaurant,restaurant|food|point_of_interest|establishment,...,82,5,44,88,25,31,14,4.371429,83.214286,5.223270
4,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27 Degree North Restaurant,"Shree Krishna Sadan, Chhakku Bakku Marg, Kathm...",27.688812,85.334080,4.7,43.0,NaN,restaurant,restaurant|food|point_of_interest|establishment,...,66,13,18,65,29,7,47,4.270213,200.893617,35.077195

In [20]:
df.describe()

,latitude,longitude,restaurant_rating,user_rating_count,bank_count_500m,bus_stop_count_500m,cinema_count_500m,clinic_count_500m,college_count_500m,hospital_count_500m,...,office_count_500m,parking_space_count_500m,recreation_count_500m,retail_count_500m,school_count_500m,temple_count_500m,competitor_count_500m,avg_restaurant_rating_500m,avg_review_ratings_500m,nearest_restaurant_m
count,1472.000000,1472.000000,1420.000000,1420.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,...,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1472.000000,1432.000000,1432.000000,1472.000000
mean,27.693003,85.339722,4.426620,145.483099,32.427310,2.945652,1.129076,34.055027,17.059103,11.012228,...,49.516304,7.817255,24.146739,65.887908,25.843071,30.263587,40.828804,4.416182,151.016679,100.009680
std,0.020987,0.041024,0.520025,327.783201,33.342099,3.564464,1.668168,28.057973,19.330252,9.750727,...,38.595548,8.499604,22.664435,36.462533,18.148956,35.078331,34.428626,0.195568,103.766305,214.922051
min,27.612834,85.253978,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,27.674700,85.311687,4.100000,9.000000,6.000000,0.000000,0.000000,13.000000,3.000000,4.000000,...,15.000000,1.000000,13.000000,46.000000,13.000000,5.000000,11.000000,4.317803,68.812500,18.443234
50%,27.688952,85.327905,4.500000,35.000000,18.000000,2.000000,0.000000,28.000000,10.000000,9.000000,...,46.500000,4.000000,18.000000,66.000000,23.500000,16.000000,31.000000,4.416905,136.675347,42.725668
75%,27.713084,85.361497,4.800000,132.000000,55.000000,4.000000,2.000000,48.000000,26.000000,14.000000,...,86.000000,12.000000,29.000000,90.250000,37.000000,42.000000,61.000000,4.522826,217.055556,106.203259
max,27.748779,85.458855,5.000000,4891.000000,152.000000,22.000000,8.000000,126.000000,82.000000,54.000000,...,151.000000,40.000000,105.000000,160.000000,86.000000,156.000000,123.000000,5.000000,1471.000000,4327.573897

## Check dataset info

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1472 entries, 0 to 1471
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   place_id                    1472 non-null   str
 1   restaurant_name             1472 non-null   str
 2   address                     1472 non-null   str
 3   latitude                    1472 non-null   float64
 4   longitude                   1472 non-null   float64
 5   restaurant_rating           1420 non-null   float64
 6   user_rating_count           1420 non-null   float64
 7   price_level                 168 non-null    str
 8   primary_type                1466 non-null   str
 9   all_types                   1472 non-null   str
 10  search_area                 1472 non-null   str
 11  searched_as                 1472 non-null   str
 12  reviews                     1366 non-null   str
 13  bank_count_500m             1472 non-null   int64
 14  bus_stop_count_500m         1472 non-null   int64
 15  cinema_count_500m           1472 non-null   int64
 16  clinic_count_500m           1472 non-null   int64
 17  college_count_500m          1472 non-null   int64
 18  hospital_count_500m         1472 non-null   int64
 19  museum_count_500m           1472 non-null   int64
 20  office_count_500m           1472 non-null   int64
 21  parking_space_count_500m    1472 non-null   int64
 22  recreation_count_500m       1472 non-null   int64
 23  retail_count_500m           1472 non-null   int64
 24  school_count_500m           1472 non-null   int64
 25  temple_count_500m           1472 non-null   int64
 26  competitor_count_500m       1472 non-null   int64
 27  avg_restaurant_rating_500m  1432 non-null   float64
 28  avg_review_ratings_500m     1432 non-null   float64
 29  nearest_restaurant_m        1472 non-null   float64
dtypes: float64(7), int64(14), str(9)
memory usage: 345.1 KB

### Check for missing values

In [22]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

restaurant_rating               52
user_rating_count               52
price_level                   1304
primary_type                     6
reviews                        106
avg_restaurant_rating_500m      40
avg_review_ratings_500m         40
dtype: int64

### Dropping the colummn price_level

In [23]:
df.drop(columns=["price_level"], inplace=True)

### Dropping the rows with missing values

In [25]:
# Drop rows with missing values in the specified columns
df = df.dropna(subset=[
    "user_rating_count",
    "avg_restaurant_rating_500m",
    "avg_review_ratings_500m",
    "reviews",
]).reset_index(drop=True)

# Verify the result
print("New shape:", df.shape)
print("Remaining missing values:")
print(df[[
    "user_rating_count",
    "avg_restaurant_rating_500m",
    "avg_review_ratings_500m",
    "reviews",
]].isnull().sum())

New shape: (1330, 29)
Remaining missing values:
user_rating_count             0
avg_restaurant_rating_500m    0
avg_review_ratings_500m       0
reviews                       0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   place_id                    1330 non-null   str
 1   restaurant_name             1330 non-null   str
 2   address                     1330 non-null   str
 3   latitude                    1330 non-null   float64
 4   longitude                   1330 non-null   float64
 5   restaurant_rating           1330 non-null   float64
 6   user_rating_count           1330 non-null   float64
 7   primary_type                1324 non-null   str
 8   all_types                   1330 non-null   str
 9   search_area                 1330 non-null   str
 10  searched_as                 1330 non-null   str
 11  reviews                     1330 non-null   str
 12  bank_count_500m             1330 non-null   int64
 13  bus_stop_count_500m         1330 non-null   int64
 14  cinema_count_500m           1330 non-null   int64
 15  clinic_count_500m           1330 non-null   int64
 16  college_count_500m          1330 non-null   int64
 17  hospital_count_500m         1330 non-null   int64
 18  museum_count_500m           1330 non-null   int64
 19  office_count_500m           1330 non-null   int64
 20  parking_space_count_500m    1330 non-null   int64
 21  recreation_count_500m       1330 non-null   int64
 22  retail_count_500m           1330 non-null   int64
 23  school_count_500m           1330 non-null   int64
 24  temple_count_500m           1330 non-null   int64
 25  competitor_count_500m       1330 non-null   int64
 26  avg_restaurant_rating_500m  1330 non-null   float64
 27  avg_review_ratings_500m     1330 non-null   float64
 28  nearest_restaurant_m        1330 non-null   float64
dtypes: float64(7), int64(14), str(8)
memory usage: 301.5 KB

### printing the name of restaurant with the missing primary type for manual imputation

In [27]:
# Show rows where primary_type is missing
df[df["primary_type"].isna()][["restaurant_name", "primary_type"]]

                                     restaurant_name primary_type
285                                      Cafe Mitini          NaN
346                                Titanic Dance Bar          NaN
497                       Arabica Brew Coffee School          NaN
644                        Srisha's Dairy and Bakery          NaN
882   The Baristas Coffee School (Kumaripati Branch)          NaN
1222    The Baristas Coffee School (Lazimpat Branch)          NaN

### all the unique  primary type

In [28]:
# Show all unique primary types
print(df["primary_type"].dropna().unique())

<StringArray>
[                'restaurant',        'barbecue_restaurant',
          'family_restaurant',       'fast_food_restaurant',
         'tibetan_restaurant',       'hamburger_restaurant',
          'korean_restaurant',           'asian_restaurant',
                       'cafe',                'coffee_shop',
                  'cafeteria', 'korean_barbecue_restaurant',
                 'sports_bar',                        'bar',
                 'lounge_bar',              'bar_and_grill',
                  'cake_shop',                     'bakery',
    'educational_institution',           'ramen_restaurant',
          'indian_restaurant',                'steak_house',
            'thai_restaurant',           'pizza_restaurant',
        'japanese_restaurant',        'shawarma_restaurant',
         'western_restaurant',           'halal_restaurant',
                 'food_store',                        'pub',
               'dessert_shop',                      'store',
                      'hotel',      'vegetarian_restaurant',
                'guest_house',         'chinese_restaurant',
               'manufacturer',         'italian_restaurant',
                 'food_court',    'north_indian_restaurant',
         'indoor_golf_course',               'cocktail_bar',
          'brunch_restaurant',                  'tea_house',
    'asian_fusion_restaurant',         'spanish_restaurant',
           'vegan_restaurant',              'meal_takeaway',
    'south_indian_restaurant',                'noodle_shop',
     'fine_dining_restaurant',  'latin_american_restaurant',
        'american_restaurant',                  'irish_pub',
            'coffee_roastery']
Length: 55, dtype: str

### Manual Imputation of Missing primary_type Values

In [29]:
df.loc[df["restaurant_name"] == "Cafe Mitini", "primary_type"] = "cafe"

df.loc[df["restaurant_name"] == "Titanic Dance Bar", "primary_type"] = "bar"

df.loc[df["restaurant_name"] == "Arabica Brew Coffee School", "primary_type"] = "coffee_shop"

df.loc[df["restaurant_name"] == "Srisha's Dairy and Bakery", "primary_type"] = "bakery"

df.loc[df["restaurant_name"] == "The Baristas Coffee School (Kumaripati Branch)", "primary_type"] = "coffee_shop"

df.loc[df["restaurant_name"] == "The Baristas Coffee School (Lazimpat Branch)", "primary_type"] = "coffee_shop"

### Check for Duplicate Rows

In [30]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

#### Check Data Types

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   place_id                    1330 non-null   str
 1   restaurant_name             1330 non-null   str
 2   address                     1330 non-null   str
 3   latitude                    1330 non-null   float64
 4   longitude                   1330 non-null   float64
 5   restaurant_rating           1330 non-null   float64
 6   user_rating_count           1330 non-null   float64
 7   primary_type                1330 non-null   str
 8   all_types                   1330 non-null   str
 9   search_area                 1330 non-null   str
 10  searched_as                 1330 non-null   str
 11  reviews                     1330 non-null   str
 12  bank_count_500m             1330 non-null   int64
 13  bus_stop_count_500m         1330 non-null   int64
 14  cinema_count_500m           1330 non-null   int64
 15  clinic_count_500m           1330 non-null   int64
 16  college_count_500m          1330 non-null   int64
 17  hospital_count_500m         1330 non-null   int64
 18  museum_count_500m           1330 non-null   int64
 19  office_count_500m           1330 non-null   int64
 20  parking_space_count_500m    1330 non-null   int64
 21  recreation_count_500m       1330 non-null   int64
 22  retail_count_500m           1330 non-null   int64
 23  school_count_500m           1330 non-null   int64
 24  temple_count_500m           1330 non-null   int64
 25  competitor_count_500m       1330 non-null   int64
 26  avg_restaurant_rating_500m  1330 non-null   float64
 27  avg_review_ratings_500m     1330 non-null   float64
 28  nearest_restaurant_m        1330 non-null   float64
dtypes: float64(7), int64(14), str(8)
memory usage: 301.5 KB

### Data Validation

In [32]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

latitude: Min = 27.6450059, Max = 27.7463406
longitude: Min = 85.2627739, Max = 85.44651549999999
restaurant_rating: Min = 1.0, Max = 5.0
user_rating_count: Min = 1.0, Max = 4891.0
bank_count_500m: Min = 0, Max = 152
bus_stop_count_500m: Min = 0, Max = 22
cinema_count_500m: Min = 0, Max = 8
clinic_count_500m: Min = 0, Max = 125
college_count_500m: Min = 0, Max = 82
hospital_count_500m: Min = 0, Max = 54
museum_count_500m: Min = 0, Max = 72
office_count_500m: Min = 0, Max = 151
parking_space_count_500m: Min = 0, Max = 40
recreation_count_500m: Min = 0, Max = 105
retail_count_500m: Min = 0, Max = 160
school_count_500m: Min = 0, Max = 86
temple_count_500m: Min = 0, Max = 156
competitor_count_500m: Min = 1, Max = 123
avg_restaurant_rating_500m: Min = 1.0, Max = 5.0
avg_review_ratings_500m: Min = 1.0, Max = 1471.0
nearest_restaurant_m: Min = 0.0, Max = 480.2857727516201

In [33]:
# Save the cleaned dataset
df.to_csv("../data/processed/cleaned_final_dataset.csv", index=False)

print("Dataset saved successfully as 'cleaned_final_dataset.csv'")

Dataset saved successfully as 'cleaned_final_dataset.csv'

In [34]:
# Verify the saved dataset
df_check = pd.read_csv("../data/processed/cleaned_final_dataset.csv")
print(df_check.shape)
df_check.head()

(1330, 29)

,place_id,restaurant_name,address,latitude,longitude,restaurant_rating,user_rating_count,primary_type,all_types,search_area,...,office_count_500m,parking_space_count_500m,recreation_count_500m,retail_count_500m,school_count_500m,temple_count_500m,competitor_count_500m,avg_restaurant_rating_500m,avg_review_ratings_500m,nearest_restaurant_m
0,ChIJsZ5mY70Z6zkRRBczgL9a8ms,JAR - Just Another Restaurant,"Pipal Bot Marg, Kathmandu 56900, Nepal",27.699546,85.337687,4.3,443.0,restaurant,restaurant|food|point_of_interest|establishment,Baneshwor,...,53,5,21,52,35,15,20,4.265000,87.700000,66.240461
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,Drishya Lounge - Best Lounge in New Baneshwor,"Devkota Sadak, Kathmandu 44600, Nepal",27.692262,85.336472,4.4,1180.0,restaurant,restaurant|food|point_of_interest|establishment,Baneshwor,...,66,6,19,83,48,17,44,4.247727,159.477273,3.882433
2,ChIJTdMmLgAZ6zkR84zXOWwdgPE,Pink Putali Restaurant & Bar,"4 Chhakku Bakku Marg, Kathmandu 44600, Nepal",27.689064,85.334295,4.8,90.0,restaurant,restaurant|food|point_of_interest|establishment,Baneshwor,...,67,11,18,67,30,6,47,4.234043,204.255319,35.077195
3,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,Munch N More Restaurant and Bar,"Janata Sadak, Kathmandu 44600, Nepal",27.681549,85.341340,4.9,60.0,restaurant,restaurant|food|point_of_interest|establishment,Baneshwor,...,82,5,44,88,25,31,14,4.371429,83.214286,5.223270
4,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27 Degree North Restaurant,"Shree Krishna Sadan, Chhakku Bakku Marg, Kathm...",27.688812,85.334080,4.7,43.0,restaurant,restaurant|food|point_of_interest|establishment,Baneshwor,...,66,13,18,65,29,7,47,4.270213,200.893617,35.077195